name: Atualizar Changelog

on:
  push:
    branches:
      - main

jobs:
  update-changelog:
    if: github.actor != 'github-actions[bot]' && !contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configurar Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Executar script de geração de changelog
        run: bash CHANGELOG_GEN.sh

      - name: Verificar se o changelog foi alterado
        id: changelog-check
        run: |
          git diff --exit-code CHANGELOG.md || echo "changed=true" >> $GITHUB_ENV

      - name: Commit e push das alterações
        if: env.changed == 'true'
        run: |
          git add CHANGELOG.md
          git commit --amend --no-edit
          git push --force-with-lease origin main

    permissions:
      contents: write