name: TESTE DE CONEXÃO SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
        chmod 600 private_key
        eval "$(ssh-agent -s)"
        ssh-add private_key

    - name: Testar conexão SSH
      run: |
        ssh -v -p 2222 \
        -o StrictHostKeyChecking=no \
        ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo 'Conexão SSH bem-sucedida!'"

    - name: Enviar arquivo de exemplo
      run: |
        echo "Este é um arquivo de exemplo." > exemplo.txt
        scp -v -P 2222 \
        -o StrictHostKeyChecking=no \
        exemplo.txt ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home2/${{ secrets.SSH_USER }}/
